### ISSUE TITLE
unable to build for non-std targets

### ISSUE THREAD

**Issue by osimmac** [ua-kxie/pid-ctrl#2] opened 2023-01-02 10:58 UTC
get errors about not being able to compile num-traits for all sorts of reasons. in the cargo.toml of pid-ctrl, this must be added:
`[dependencies.num-traits]`
`version = "0.2.15"`
`default-features = false`
`# features = ["libm"]    # <--- Uncomment if you wish to use 'Float' and 'Real' without std`

by doing that, it seems to build fine

**Comment by Iraeis** [comment] 2023-01-02 12:54
I see you've already fixed this issue in a fork. Did you want to sync your fork back upstream?

**Comment by osimmac** [comment] 2023-01-02 20:45
Sure! that'd be cool. I'll make a pr: #3

**Comment by Iraeis** [comment] 2023-01-03 03:46
merged. I also found and removed references to num-traits float (instead of floatcore)

If you could kindly confirm on your end that the issue is fixed and close the issue.

**Comment by Iraeis** [comment] 2023-01-06 12:29
closing without confirmation

**Closed as completed by Iraeis** 2023-01-06 12:29 UTC
